"""add timestamps

Revision ID: 247af5b66bc4
Revises: e54f3dcbc0e0
Create Date: 2025-11-11 03:24:50.957021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '247af5b66bc4'
down_revision: Union[str, Sequence[str], None] = 'e54f3dcbc0e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('vote_topics', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('vote_topics', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('votes_options', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('votes_options', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('votes_options', 'updated_at')
    op.drop_column('votes_options', 'created_at')
    op.drop_column('vote_topics', 'updated_at')
    op.drop_column('vote_topics', 'created_at')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
