"""update cascaded vote models

Revision ID: 91301e7f77d4
Revises: b6235ec1f57c
Create Date: 2025-11-30 00:42:34.270953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91301e7f77d4'
down_revision: Union[str, Sequence[str], None] = 'b6235ec1f57c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('votes_options_vote_topic_id_fkey'), 'votes_options', type_='foreignkey')
    op.create_foreign_key(None, 'votes_options', 'vote_topics', ['vote_topic_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'votes_options', type_='foreignkey')
    op.create_foreign_key(op.f('votes_options_vote_topic_id_fkey'), 'votes_options', 'vote_topics', ['vote_topic_id'], ['id'])
    # ### end Alembic commands ###
