"""update cascaded models

Revision ID: b6235ec1f57c
Revises: e5dd2889d5f5
Create Date: 2025-11-25 16:57:59.865292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6235ec1f57c'
down_revision: Union[str, Sequence[str], None] = 'e5dd2889d5f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('vote_topics_created_by_fkey'), 'vote_topics', type_='foreignkey')
    op.create_foreign_key(None, 'vote_topics', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vote_topics', type_='foreignkey')
    op.create_foreign_key(op.f('vote_topics_created_by_fkey'), 'vote_topics', 'users', ['created_by'], ['id'])
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
