"""add models

Revision ID: e54f3dcbc0e0
Revises: 1dd8ac4f3524
Create Date: 2025-11-08 21:09:12.096228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e54f3dcbc0e0'
down_revision: Union[str, Sequence[str], None] = '1dd8ac4f3524'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vote_topics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voters_association',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('vote_topic_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vote_topic_id'], ['vote_topics.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'vote_topic_id')
    )
    op.create_table('votes_options',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vote_option', sa.String(length=100), nullable=False),
    sa.Column('vote_count', sa.Integer(), nullable=False),
    sa.Column('vote_topic_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['vote_topic_id'], ['vote_topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes_options')
    op.drop_table('voters_association')
    op.drop_table('vote_topics')
    op.drop_table('users')
    # ### end Alembic commands ###
