"""update refresh token model

Revision ID: e5dd2889d5f5
Revises: bab5101fc400
Create Date: 2025-11-17 19:40:05.936633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5dd2889d5f5'
down_revision: Union[str, Sequence[str], None] = 'bab5101fc400'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('last_used_at', sa.DateTime(), nullable=False))
    op.drop_column('refresh_tokens', 'expires_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('refresh_tokens', 'last_used_at')
    # ### end Alembic commands ###
